=== yoanes/crf/src/resources/au/com/sensis/mobile/crf/config/crf-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://mobile.sensis.com.au/web/crf/config"
    targetNamespace="http://mobile.sensis.com.au/web/crf/config"
    elementFormDefault="unqualified" attributeFormDefault="unqualified"
    version="1.0">

    <xs:annotation>
        <xs:documentation>
            Schema for the Content Rendering Platform resources config file. 
        </xs:documentation>
    </xs:annotation>

    <!-- ================================================================== -->
    
    <xs:element name="ui-configuration" type="UiConfiguration" />
    
    <xs:complexType name="UiConfiguration">
        <xs:sequence>
            <xs:element name="config-path" type="xs:string" />
            <xs:element name="groups" type="Groups" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Groups">
        <xs:annotation>
            <xs:documentation>
                Encapsulates a sequence of groups.
            </xs:documentation>
        </xs:annotation>
        
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="group" type="Group" /> 
                <xs:element name="import" type="Import" /> 
            </xs:choice>
            <xs:element name="default-group" type="DefaultGroup" 
                minOccurs="1" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Group">
        <xs:annotation>
            <xs:documentation>
                Represents a group of resources.
            </xs:documentation>
        </xs:annotation>

        <xs:attribute name="name" type="xs:string" use="required"/>        
        <xs:attribute name="expr" type="xs:string" use="required" />        
    </xs:complexType>
    
    <xs:complexType name="DefaultGroup">
        <xs:annotation>
            <xs:documentation>
                Special default group of resources.
            </xs:documentation>
        </xs:annotation>

        <xs:attribute name="name" type="xs:string" use="required" />        
    </xs:complexType>
    
    <xs:complexType name="Import">
        <xs:annotation>
            <xs:documentation>
                Imports a group(s) from other files. At least one of "name", "fromName"
                or "fromConfigPath" must be set. 
            </xs:documentation>
        </xs:annotation>

        <xs:attribute name="name" type="xs:string" use="optional">
            <xs:annotation>
                <xs:documentation>
                    Name that the (single) imported group will be given in this config file. 
                    If only one of "name" and "fromName" is given, the other will automatically 
                    use the same value.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>        
        <xs:attribute name="fromConfigPath" type="xs:string" use="optional">        
            <xs:annotation>
                <xs:documentation>
                    Config path (ie. namespace) of the file from which to import a group(s).
                    If neither "name" or "fromName" is specified, all groups will be imported. 
                    If config path is not specified, it defaults to "global/devices" but note that
                    at least one of "name", "fromName" or "fromConfigPath" must be explicitly set. 
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="fromName" type="xs:string" use="optional">
            <xs:annotation>
                <xs:documentation>
                    Name of the (single) group to import. If only one of "name" and "fromName" is
                    given, the other will automatically use the same value.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    
</xs:schema>

=== yoanes/crf/showcase/web/WEB-INF/crf-config/default-crf-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<crf:ui-configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:crf="http://mobile.sensis.com.au/web/crf/config"
         xsi:schemaLocation="http://mobile.sensis.com.au/web/crf/config crf-config.xsd">

    <config-path></config-path>
    <groups>
        <!-- Device specific groups. -->
        <group name="iphone-ipod-os2" expr="device.name =~ '.*iPhone.*' and device.userAgent =~ '.*OS 2_.*'" />
        <group name="iphone-ipod" expr="device.name =~ '.*iPhone.*'" />
        <group name="nokia7600" expr = "device.userAgent =~ '.*Nokia7600.*'" />        
        <group name="Apple-iPad" expr="device.name =~ '.*iPad.*'" />
	 	<group name="Samsung-GT-C5220" expr="device.name =~ '.*Samsung.*C5220.*'" />
	 	<group name="Samsung-SGH-A412" expr="device.name =~ '.*Samsung.*SGH.*A412.*'" />
	 	<group name="Samsung-SGH-F480" expr="device.name =~ '.*Samsung.*SGH.*F480.*'" />
	 	<group name="SAGEM-HomeManager" expr="device.name =~ '.*SAGEM-HomeManager.*'" />
		<group name="BlackBerry-9700" expr="device.name =~ '.*BlackBerry9700.*'" />
		<group name="HTC-Desire" expr="device.isA('HTC-A8183')" />
		<!--<group name="highend-maps" expr="device.isOneOf('HTC-A8183', 'SonyEricsson-X10')" />
		 <group name="HTC-Desire" expr="device.name =~ '.*HTC.*Desire.*A8183.*'" /> -->
		<group name="SonyEricsson-Z750i" expr="device.name =~ '.*SonyEricsson.*Z750i.*'" />

		<!-- Browser family groups. -->
		<group name="LG-Obigo" expr="device.userAgent =~ '.*LG.*Obigo.*'" />
	 	<group name="Nokia-Webkit" expr="device.userAgent =~ '.*Nokia.*AppleWebKit.*'" />        
        <group name="applewebkit" expr="device.userAgent =~ '.*AppleWebKit.*'" />
        <group name="webkit" expr="device.userAgent =~ '.*WebKit.*'" />
        <group name="Apple" expr="device.name =~ '.*Apple.*'" />
	 	<group name="Android" expr="device.userAgent =~ '.*Android.*'" />

        <!-- Image category groups. -->
        <group name="HD800" expr="device.imageCategory eq 'HD800'" />
        <group name="HD640" expr="device.imageCategory eq 'HD640'" />
        <group name="HD480" expr="device.imageCategory eq 'HD480'" />
        <group name="L" expr="device.imageCategory eq 'L'" />
        <group name="M" expr="device.imageCategory eq 'M'" />
        <group name="S" expr="device.imageCategory eq 'S'" />
        <group name="XS" expr="device.imageCategory eq 'XS'" />
        
        <group name="clickToCallSupported" expr="device.clickToCallSupported" />
        
        <!-- Test usage of the custom CRF inAllGroups function. -->
        <group name="clickToCallSupported-hd640" expr="inAllGroups(device, 'clickToCallSupported', 'HD640')" />
        
        <default-group name="default" />
    </groups>

</crf:ui-configuration>

=== yoanes/crf/src/resources/au/com/sensis/mobile/crf/config/global-image-categories-crf-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<crf:ui-configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:crf="http://mobile.sensis.com.au/web/crf/config"
         xsi:schemaLocation="http://mobile.sensis.com.au/web/crf/config crf-config.xsd">

    <config-path>global/imageCategories</config-path>
    <groups>
        <!--  Image category groups -->
        <group name="HD800" expr="device.imageCategory eq 'HD800' or 
                                  device.imageCategory eq 'HD1024'"/>
                                  
        <group name="HD640" expr="device.imageCategory eq 'HD640'" />
        
        <group name="L" expr="device.imageCategory eq 'L' or
                              device.imageCategory eq 'HD480'" />
                              
        <group name="M" expr="device.imageCategory eq 'M'" />
        <group name="S" expr="device.imageCategory eq 'S'" />
        <group name="XS" expr="device.imageCategory eq 'XS'" />
        
        <default-group name="default" />        
    </groups>

</crf:ui-configuration>

=== yoanes/crf/test/unit/resources/au/com/sensis/mobile/crf/config/crf-config-multiple-valid-groups.xml
<?xml version="1.0" encoding="UTF-8"?>

<crf:ui-configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:crf="http://mobile.sensis.com.au/web/crf/config"
         xsi:schemaLocation="http://mobile.sensis.com.au/web/crf/config crf-config.xsd">

    <config-path></config-path>
    <groups>
        <group name="iphone" expr="device.name =~ '.*iPhone.*'" />
        <group name="android-os" expr="device.isA('Android-OS') or device.isA('Android-Emulator')" />
        <group name="ipad" expr = "device.isA('Apple-iPad')" />
        <group name="applewebkit" expr="device.userAgent =~ '.*AppleWebKit.*'" />
        <group name="L" expr="device.imageCategory eq 'L'" />
        <group name="M" expr="device.imageCategory eq 'M'" />
        
        <default-group name="default" />
    </groups>

</crf:ui-configuration>

=== yoanes/crf/test/unit/resources/au/com/sensis/mobile/crf/config/crf-config-import-global-groups.xml
<?xml version="1.0" encoding="UTF-8"?>

<crf:ui-configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:crf="http://mobile.sensis.com.au/web/crf/config"
         xsi:schemaLocation="http://mobile.sensis.com.au/web/crf/config crf-config.xsd">

    <config-path></config-path>
    <groups>
        <group name="iphone" expr="device.name =~ '.*iPhone.*'" />

        <!-- Import group from default global config file. -->        
        <import name="android-os"/>

        <!-- Import group from global config file explicitly. -->        
        <import name="ipad"  from="global/extraDevices"/>
        
        <group name="applewebkit" expr="device.userAgent =~ '.*AppleWebKit.*'" />
        
        <!-- Import an entire config file. -->
        <import from="global/imageCategories" />
        
        <default-group name="default" />
    </groups>

</crf:ui-configuration>

=== yoanes/crf/showcase/web/WEB-INF/crf-config/au/com/sensis/mobile/web/component/map/crf/map-crf-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<crf:ui-configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:crf="http://mobile.sensis.com.au/web/crf/config"
         xsi:schemaLocation="http://mobile.sensis.com.au/web/crf/config crf-config.xsd">

    <config-path>selenium/component/map</config-path>
    <groups>
        <!-- Device specific groups. -->
        <group name="android-os" expr="device.isA('Android-OS') or device.isA('Android-Emulator')" />
        <group name="iphone-ipod" expr="device.name =~ '.*iPhone.*'" />
        
        <!-- 
          - NOTE: completely fabricated group name to ensure that resources picked up from this group
          - were not resolved by the default crf-config.xml. 
          -->
        <!-- Test usage of the custom CRF inAnyGroup function. -->
        <group name="mapComponent-advanced" expr="inAnyGroup('android-os', 'iphone-ipod')" />
        
        <!-- Browser family groups. -->        
        <group name="applewebkit" expr="device.userAgent =~ '.*AppleWebKit.*'" />
        <group name="webkit" expr="device.userAgent =~ '.*WebKit.*'" />
        
        <default-group name="default" />
    </groups>

</crf:ui-configuration>

=== yoanes/crf/src/resources/au/com/sensis/mobile/crf/config/global-devices-crf-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<crf:ui-configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:crf="http://mobile.sensis.com.au/web/crf/config"
         xsi:schemaLocation="http://mobile.sensis.com.au/web/crf/config crf-config.xsd">

    <config-path>global/devices</config-path>
    <groups>

        <!-- Apple devices. -->
        <group name="iphone-ipod-os2-x" expr="(device.isA('Apple-iPhone') or device.isA('Apple-iPod-Touch')) and device.userAgent =~ '.*OS 2_.*'" />
        <group name="iphone-ipod-os3-x" expr="(device.isA('Apple-iPhone') or device.isA('Apple-iPod-Touch')) and device.userAgent =~ '.*OS 3_.*'" />
        <group name="iphone-ipod-os4-x" expr="(device.isA('Apple-iPhone') or device.isA('Apple-iPod-Touch')) and device.userAgent =~ '.*OS 4_.*'" />
        
        <group name="iphone-ipod-upto-os3-x" expr="inAnyGroup('iphone-ipod-os-2-x', 'iphone-ipod-os-3-x')" />
        <group name="iphone-ipod-upto-os4-x" expr="inAnyGroup('iphone-ipod-upto-os3-x', 'iphone-ipod-os-4-x')" />
        <group name="iphone-ipod" expr="device.isA('Apple-iPhone') or device.isA('Apple-iPod-Touch')" />
        
        <group name="ipad-os3-x" expr="device.isA('Apple-iPad') and device.userAgent =~ '.*OS 3_.*'" />
        <group name="ipad-os4-x" expr="device.isA('Apple-iPad') and device.userAgent =~ '.*OS 4_.*'" />        
        
        <group name="ipad-upto-os4-x" expr="inAnyGroup('ipad-os3-x', 'ipad-os4-x')" />
        <group name="ipad" expr="device.isA('Apple-iPad')" />
        
        <group name="apple" expr="device.isA('Apple')" />
        
        <!-- Android devices. -->
        <group name="sex10" expr="device.isA('SonyEricsson-X10')" />
        <group name="sex10mini" expr="device.isA('SE-X10-mini')" />
        <group name="htc-desire" expr="device.isA('HTC-Desire') or device.isA('HTC-A8183')" />

        <group name="android-os1-x" expr="device.isA('Android-OS') and device.userAgent =~ '.*Android 1\..*'" />        
        <group name="android-os2-x" expr="device.isA('Android-OS') and device.userAgent =~ '.*Android 2\..*'" />
        
        <group name="android-upto-os2-x" expr="inAnyGroup('android-os1-x', 'android-os2-x')" />
        
        <group name="android-os" expr="device.isA('Android-OS')" />
        
        <!-- Windows 7. -->
        <group name="windows7" expr="device.isA('SP-WindowsMobile-7')" />
        
        <!-- Blackberry -->
        <group name="blackberry" expr="device.isA('RIM-Blackberry')" />
        
        <!-- thub. -->
        <group name="thub" expr="device.isA('SAGEM-HomeManager')" />
        
        <!-- Nokia devices. -->
        <group name="nokiaS60DP3" expr="device.isA('Nokia-Series60-DP3_0')" />
        <group name="nokiaS60DP5" expr="device.isA('Nokia-Series60-DP5_0')" />
        
        <!-- Samsung devices. -->
        <group name="samsungC5220" expr="device.isA('Samsung-GT-C5220') " />        
        
        <!-- PC. -->
        <group name="mozilla" expr="device.isA('PC-Win32-Mozilla') or
                                    device.isA('PC-MacOS-Mozilla') or
                                    device.isA('PC-UNIX-Mozilla')"/>
                                    
        <group name="opera" expr="device.isA('PC-Win32-Opera') or
                                  device.isA('PC-MacOS-Opera') or
                                  device.isA('PC-UNIX-Opera')"/>
        
        <default-group name="default" />
    </groups>

</crf:ui-configuration>
